### ISSUE TITLE
Downloads fail when filenames contain certain characters

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#438]
Particularly an apostrophe, but probably others.  The remote client returns a "File not shared" rejection which is almost certainly a failure to request the correct filename.

**Comment by mathiascode** [comment]
This was an issue Nicotine+ had until recently. with Soulseek NS clients in particular. Sending file name/search strings encoded as iso-8859-1 instead of utf-8 resolves most of the file name matching issues, which also leads to more search results sent from Soulseek NS clients. See https://github.com/Nicotine-Plus/nicotine-plus/pull/760

There are some rarer cases that still trigger the "File not shared" status, even in SoulseekQt, but it would seem like the file names are completely screwed up in these cases.

**Comment by jpdillingham** [comment]
Thanks for chiming in.  Some investigation:

Soulseek QT fully supports UTF-8.  This has been known, but I'm stating it for anyone that might stumble upon this in the future.

Soulseek NS supports only ISO-8859-1, and I think the limitation is introduced when it reads the filename from disk.  Files containing UTF-8 characters also do not report any attributes, such as bitrate, which leads me to believe that NS was not capable of opening and reading the file.

Soulseek NS will not display UTF-8 when browsing local shares and can't download files from/to itself (it can with non-UTF-8 filenames). Examining the raw data from responses from Soulseek NS reveals that UTF-8 characters are transmitted as `?`.

This all leads to the (probably obvious, but again it is prudent to state) conclusion that Soulseek NS simply can not handle filenames containing UTF-8 in any capacity, and that this limitation is the local file handling of the client instead of a network issue with encoding.

I think your solution of trying to use ISO-8859-1 and falling back to UTF-8 is a good one, however I can't get .NET to cooperate this morning; it happily decodes UTF-8 as ISO.
