### ISSUE TITLE
First Impression

### ISSUE THREAD

**Issue by vKnmnn** [jpdillingham/Soulseek.NET#470]
Hi! coming from the lidarr-issue i tested this app a bit. Great work so far! 

Here's a few things i noticed:
- clicking another tab (downloads/uploads...) while slsk.net is searching cancels the search. When i come back to the search tab, there are no results. Maybe this is a feature, but i wasn’t sure
- searches cannot be refined, as we are not able to click in the search box after results have been returned. you always have to reenter the search query.
- The number of search results seems quite small (those displayed first, before clicking on "show more"). That number could be configurable.
- I sometimes get this message in the log **[DIAGNOSTIC:ServerMessageHandler] [Warning] Error handling server message: CannotConnect; Failed to read an integer (4 bytes) from position 4 of the message
**

**Comment by vKnmnn** [comment]
I have also noticed the download progress-labels have a bug:  in the first second or so, the progress can show something like 530.22/112MB. I'm assumung the 530 in that case would be kB instead of MB

**Comment by jpdillingham** [comment]
Thanks for taking the time to give me this feedback; it's all stuff that I'll eventually address in [slskd](https://github.com/slskd/slskd) once I get the repo fully initialized.  Most of this is due to the quick and dirty nature of the implementation; the example in this repo is primarily a front-end for my testing and I took it a bit farther than was necessary.
