### ISSUE TITLE
.NET Framework Port?

### ISSUE THREAD

**Issue by Runnin-N-Gunnin** [jpdillingham/Soulseek.NET#474]
I'd like to use this in a WinForms application, .NET Framework 4.7.2 so I tried porting it by creating a new .NET Framework class library and then re-importing all the .cs-files and manually fix errors that show up.

I'm at ~11 errors. Unfortunately I'm having trouble with the Null Coalescing Assignment operator ("??="). It's not supported in VS2017 (C# 7.3?)

Any way to get this working?

Thanks!

**Comment by jpdillingham** [comment]
I created a new branch targeting .NET Standard 2.0: https://github.com/jpdillingham/Soulseek.NET/compare/netstandard20, this builds and all of the unit tests pass.  This should work with .NET framework down to [4.6.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

I would recommend targeting .NET Core 3.1 or .NET 5 for any new winforms app so that you can use this lib straight from nuget; there's been a ton of performance improvements over framework, and the inability to use `IAsyncDisposable` with .NET standard 2.0 will impact performance a little as well.

**Comment by Runnin-N-Gunnin** [comment]
I got it working. The link you sent was useful.

In addition to the changes referenced in your link I had to make a few other (.NET Framework-specific) changes:

"??=" (ReSharper suggested: 'To Assignment' instead)
"using var ..." (removed 'using')
A switch statement had to be changed

I'll take your suggestions on using .NET Core/.NET 5 into consideration!

Thank you.

**Comment by jpdillingham** [comment]
Glad you were able to get it working.  I think you could have avoided making the changes you mentioned by setting `<LangVersion>8.0</LangVersion>` in your .csproj, but it isn't a big deal.

Regarding the `using` statements that were removed, you'll probably want to put them back using the older syntax:

```c#
using (var x = whatever)
{
    ...code that uses x
}
```

Taking these out might delay the disposal of things implementing `IDisposable` which could cause memory leaks.

**Comment by Runnin-N-Gunnin** [comment]
>  I think you could have avoided making the changes you mentioned by setting <LangVersion>8.0</LangVersion> in your .csproj, but it isn't a big deal.

I thought so too but I could not because I'm using VS2017. Changing the LangVersion would cause the project to fail to load.

> Regarding the using statements that were removed, you'll probably want to put them back using the older syntax

OK - good looking out!

Great library/project :-)
