### ISSUE TITLE
TransferRequest not answered after cancelling downloads

### ISSUE THREAD

**Issue by mathiascode** [jpdillingham/Soulseek.NET#491]
I noticed the following issue while testing transfers:

- Peer 1 on Soulseek.NET/slskd queues up a few downloads, and a transfer starts.
- Peer 1 later aborts the downloads.
- The transfer is cancelled on peer 2's end.
- Peer 2 sends a TransferRequest to upload the next file previously queued by peer 1.
- At this stage, a TransferResponse disallowing the upload should be sent. Soulseek.NET does not do this, leaving the other end hanging.

**Comment by jpdillingham** [comment]
Thanks for raising this!

**Comment by mathiascode** [comment]
Thanks! An empty reason string seems to be sent in the TransferResponse currently, while the expected value would be "Cancelled".

**Comment by jpdillingham** [comment]
I never could figure out what was supposed to happen here and your comment prompted me to think through it again.  Qt accepts these transfers if the "Accept uploads from all user list users" is checked (and the user is in the list); otherwise `Cancelled` is returned, as you stated.

I double checked what the response would be to an unsolicited upload and it is `Cancelled` in that case as well.
