### ISSUE TITLE
Incorrect file path sent in TransferRequest

### ISSUE THREAD

**Issue by mathiascode** [jpdillingham/Soulseek.NET#492]
There appears to be a mismatch in file paths sent by Soulseek.NET. While browsing shares of a Soulseek.NET user, "virtual" paths appear to be sent, e.g. "sharedfolder/subfolder/subfolder". I then request to download a file, and receive a TransferRequest with the real file path instead, e.g. "/home/user/sharedfolder/subfolder/subfolder". While SoulseekQt appears to handle such cases, Nicotine+ rejects these uploads.

Additionally, the virtual path incorrectly uses forward slashes instead of backslashes, at least on Linux. The folder path combined with the file name then looks as following: "sharedfolder/subfolder/subfolder\file.mp3".

**Comment by jpdillingham** [comment]
Not at all surprising, I fiddled with this forever so that I could use these in HTTP route parameters and eventually gave up but didn't revisit the code.

While I was messing with it I did confirm that SoulseekQt doesn't seem to care what the path is; all the issues I had were between two copies of Soulseek.NET, one on Windows and the other Linux.

I'm fairly certain that all of the implementation details are client side (that is, not within the core lib) so I'll fix this example and then port it over to slskd.

**Comment by jpdillingham** [comment]
The `latest` slskd tag should fix this. I tested with Nicotine+ both to/from search and browse results.

I'll leave this open until I can address the issue with slashes.  I tried SoulseekQt on Linux and it does use only backslashes in browse results, but I want to confirm searches also just to cover bases.  Once this is implemented the treeview in Nicotine+ should be fixed.

**Comment by mathiascode** [comment]
I added a fail-safe to convert forward slashes, but sending backward slashes would of course be preferred. Thanks for addressing these issues! https://github.com/Nicotine-Plus/nicotine-plus/commit/9b3a44a9f157bef1150af5ba2608de8a567b7ece
