### ISSUE TITLE
Correctly parse file size for >2 GB Soulseek NS files

### ISSUE THREAD

**Issue by mathiascode** [jpdillingham/Soulseek.NET#566]
Turns out there's a bug in Soulseek NS that results in the client sending an invalid file size value for >2 GB files. An explanation and workaround is here: https://github.com/Nicotine-Plus/nicotine-plus/commit/ada09fab6e3117faa5a1af2d29ed2777337ac4ac

**Comment by mathiascode** [comment]
Soulseek NS clients completely fall apart if file sizes exceed the unsigned integer limit (~4 GB), sending a file size of 0 instead, but this workaround is still useful if you want to avoid showing exabyte sizes for files between ~2 GB and ~4 GB.

**Comment by jpdillingham** [comment]
Interesting!  I'm struggling to find it now, but I did some work around this and concluded (perhaps erroneously) that the way to handle this was to use the size reported from search/browse results.  This is the reason the upload and download functions include a `size` parameter.

**Comment by jpdillingham** [comment]
The last time I touched this was in #346, it seems that the scope of that one was to support files larger than 4gb with Qt

**Comment by jpdillingham** [comment]
Interestingly, Soulseek NS is majorly malfunctioning with files between 2 and 4gb.  I'm not sure if I have a newer version now than when I last tested, or what.

![image](https://user-images.githubusercontent.com/17145758/124356570-490fea80-dbdc-11eb-94b1-b91700b4843b.png)

The garbled sizes are reported an instance of NS browsing itself.  The files with bad sizes are both ~3gb, and they don't show up when browsed by any other client.  The ~300mb files are both over 4gb, so still completely broken.

**Comment by mathiascode** [comment]
> sending a file size of 0 instead

I believe this conclusion was incorrect. I saw some large files reported as 0 bytes for some Soulseek NS user, but my own testing shows that the size wraps around at the integer limit.

> and concluded (perhaps erroneously) that the way to handle this was to use the size reported from search/browse results

This probably stems from the fact that SoulseekQt sends 0 byte sizes for large files in TransferRequest messages (I ignore such sizes in Nicotine+: https://github.com/Nicotine-Plus/nicotine-plus/blob/b693e57dd7c745af79a51831f9e80ae9a5271a52/pynicotine/transfers.py#L742-L748). Interestingly, Soulseek NS has no trouble correctly sending sizes >4 GB with TransferRequest messages. NS also seems to upload such files without issues, but I assume this is by chance.

> The garbled sizes are reported an instance of NS browsing itself. The files with bad sizes are both ~3gb, and they don't show up when browsed by any other client.

Nicotine+ shows these files on my end. SoulseekQt seems to filter them out when browsing shares (I assume), but shows them in search results.

Support for large files seems rather half-baked in both official clients, for whatever reason. SoulseekQt doesn't even seem to show large file sizes in the UI at all.

**Comment by jpdillingham** [comment]
I did some testing and confirmed that your fix works, so thanks for the heads up!

I had to review what I ended up doing around this since, as you said, large file support seems to have been bolted on in a weird way (probably threading a needle to maintain backwards compatibility with NS).

When initiating a download, the library allows callers to omit a length.  If this is omitted, the size sent in the transfer request sent by the other client is used.  This works fine with NS, and with Qt until the size goes above 4gb in which case it comes back as zero.  I think we're seeing the exact same things there.  

I double checked the contents of the transfer request payload to make sure there weren't any additional bytes at the end or anything, but the last 8 are indeed all zeros when Qt fails to report the size.  My hunch is that some version of NS in the past only supported 4 bytes here.

**Comment by mathiascode** [comment]
> My hunch is that some version of NS in the past only supported 4 bytes here.
Probably something along those lines. It's still strange that (at least the latest) Soulseek NS sends large sizes without issues, but I doubt we'll ever know why some decisions were made. The only post I've found with any sort of official input is this one: https://www.slsknet.org/news/node/3214
