### ISSUE TITLE
Implement speed limits for uploads and downloads

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#676]
Total upload and download transfer speeds across all active transfers can now be capped with the `maximumUploadSpeed` and `maximumDownloadSpeed` settings.  Values are specified in KiB/s.

Under the hood this value is multiplied by 1024, then divided by whatever the write and read transfer buffer sizes are, to arrive at the number of "tokens" available per second.  Tokens are then consumed on each write/read from the transfer socket.  Once tokens are exhausted all reads and writes await token replenishment, which happens once per second.

**Comment by jpdillingham** [comment]
@jackBonadies FYI!

**Comment by jackBonadies** [comment]
Thank you!  I am looking though your implementation now, so far it looks great.  I will try it out soon.  I had in the meantime written a download and upload governor myself (perhaps bad timing, though perhaps still useful for comparison and also for feedback regarding the current governor interface).  It did not use the leaky bucket algorithm.  Instead, it first calculated a default per-loop wait time based on the desired speed (similarly it used the buffer size).  Then each iteration would compare the current speed to the desired speed and increase/decrease the wait time.  A dictionary was kept for the last wait time.  It allowed per transfer max speed or global max speed.

In practice it worked quite well regarding limiting speed (the average speed was well within a percent of the desired speed).  However, I did have to modify the governor.  The governor takes a transfer and the transfer has an average speed.  The average speed only gets updated once a second.  Which means there was a significant "rubber banding" effect, since the loop would get hit far more often than the average speed would update (so the loop would repeatedly see the same number and either increase or decrease repeatedly without the average speed updating with the effects of the new wait time).  The solution is to only update the wait time when the average speed changes (which means the update may be a bit infrequent) or to use a current speed that is calculated each loop (without any alpha) and pass that in (updating the average speed without any alpha was no good, since I use the average speed for display and would prefer it smoother).  Just some feedback FWIW.

The only potential catch with the leaky bucket approach that I see, is the fact that (at least in my case) ReadAsync is not guaranteed to fill the 16kb buffer - I had tested this since I was using the buffersize as an initial wait time estimate - it usually filled it but would occasionally drop lower, not sure what factors influence this.

I owe you feedback on upload slots, apologies as I got reeled in with other work.  I read through your upload slot code and it looks great, just havent actually tested it.  Hope to do it soon.  Thanks again :)

**Comment by jpdillingham** [comment]
You raise a good point about the buffer not being filled, and I'm seeing it testing with slskd this morning.  That application uses a 256kb buffer size for transfers and actual speeds are coming out quite a bit lower than the configured limit, but not consistently.

I'll refactor the token bucket to be more granular, and add a way for consumers to "return" "unused" tokens back to the bucket, the logic being (buffer size 100 for illustration):

```
obtain 100 tokens
try to read 100 bytes from socket
unused tokens = 100 - <actual bytes read>
return unused tokens to bucket
````

I think there's some nuance here regarding when code might return tokens just before the bucket is replenished.  I think for now I'll just allow them to be dropped, as it should be a relatively small amount.

**Comment by jpdillingham** [comment]
I implemented the logic to return tokens, and still accuracy was poor.  I realized that I was setting a limit of 500 kb/s, and had a packet size of 256kb.  With a fixed packet size and the token bucket being "all or nothing", the limit was effectively 256kb, being the lowest multiple of the buffer size.

I refactored the token bucket so that if it can't grant the total number of requested tokens, it returns whatever tokens it has.  Requests still wait if the bucket is empty.

This eliminates the problems with the buffer size and allows me to control the speed down to 1kb/s and everything in between.  

The issue with "unused" tokens remains, but I tested this and only found it to be an issue with the very last packet for uploads, and the first few packets and last packet for downloads.  I think will happen transiently during downloads during network congestion, though, so I'll continue thinking about a way to solve for it.

**Comment by jpdillingham** [comment]
I added back the "return" logic this morning and have been benchmarking some transfers.  Here's one:

```
Attempted: 262144       Granted: 262144 Actual: 65536   Returned: 196608
Attempted: 262144       Granted: 262144 Actual: 65536   Returned: 196608
Attempted: 262144       Granted: 262144 Actual: 65536   Returned: 196608
Attempted: 262144       Granted: 252401 Actual: 65536   Returned: 186865
Attempted: 262144       Granted: 186865 Actual: 35040   Returned: 151825
Attempted: 262144       Granted: 151825 Actual: 29200   Returned: 122625
Attempted: 262144       Granted: 122625 Actual: 15896   Returned: 106729
Attempted: 262144       Granted: 106729 Actual: 13140   Returned: 93589
Attempted: 262144       Granted: 93589  Actual: 5840    Returned: 87749
Attempted: 262144       Granted: 87749  Actual: 8760    Returned: 78989
Attempted: 262144       Granted: 78989  Actual: 8760    Returned: 70229
Attempted: 262144       Granted: 70229  Actual: 5840    Returned: 64389
Attempted: 262144       Granted: 64389  Actual: 5840    Returned: 58549
Attempted: 262144       Granted: 58549  Actual: 2756    Returned: 55793
Attempted: 262144       Granted: 55793  Actual: 2920    Returned: 52873
Attempted: 262144       Granted: 52873  Actual: 8760    Returned: 44113
Attempted: 262144       Granted: 44113  Actual: 14600   Returned: 29513
Attempted: 262144       Granted: 29513  Actual: 8760    Returned: 20753
Attempted: 262144       Granted: 20753  Actual: 5840    Returned: 14913
Attempted: 262144       Granted: 14913  Actual: 8760    Returned: 6153
Attempted: 262144       Granted: 6153   Actual: 6153    Returned: 0
Attempted: 262144       Granted: 262144 Actual: 262144  Returned: 0
Attempted: 262144       Granted: 249856 Actual: 249856  Returned: 0
Attempted: 262144       Granted: 262144 Actual: 262144  Returned: 0
Attempted: 262144       Granted: 249856 Actual: 249856  Returned: 0
Attempted: 262144       Granted: 262144 Actual: 262144  Returned: 0
Attempted: 262144       Granted: 249856 Actual: 249856  Returned: 0
Attempted: 262144       Granted: 262144 Actual: 262144  Returned: 0
Attempted: 262144       Granted: 249856 Actual: 249856  Returned: 0
Attempted: 262144       Granted: 262144 Actual: 262144  Returned: 0
Attempted: 262144       Granted: 249856 Actual: 249856  Returned: 0
Attempted: 262144       Granted: 262144 Actual: 262144  Returned: 0
Attempted: 262144       Granted: 249856 Actual: 249856  Returned: 0
Attempted: 262144       Granted: 262144 Actual: 262144  Returned: 0
Attempted: 262144       Granted: 249856 Actual: 249856  Returned: 0
Attempted: 262144       Granted: 262144 Actual: 262144  Returned: 0
Attempted: 262144       Granted: 249856 Actual: 249856  Returned: 0
Attempted: 262144       Granted: 262144 Actual: 262144  Returned: 0
Attempted: 61489        Granted: 61489  Actual: 61489   Returned: 0
```

Attempted is the packet size (or bytes remaining at the end of the transfer), granted is the number of tokens that were retrieved from the bucket, actual is actual number of bytes read, and returned is the number of tokens put back in the bucket when the socket read fell short of the intended size.

It looks so far that the changes to allow a partial token request to be serviced, along with 'unused' tokens returned to the bucket, are allowing the desired amount of transfer pressure.  This is a single transfer, though, and next up will be benchmarking across several.  I don't anticipate problems.

I am noticing that the final speed is coming out about 5-10% higher than intended.  I think that's probably just timing, but if it remains 5-10% off at higher limits (tested at 350 and 500kb/s limits) it's a problem.

**Comment by jpdillingham** [comment]
It does appear to have been timing.  I lowered the resolution of the token bucket timer to 100ms and set the capacity to 1/10th of what it was, and with a limit set to 3000kb/s transfers are completing with an average speed between 2.9 and 3.1 mb/s.

I'll get tests written and the finished version will be out this weekend.
